# Generated by Django 4.1.2 on 2023-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
