# Generated by Django 4.1.2 on 2023-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Pull-Time', 'Pull-Time'), ('Full-Time', 'Full-Time')], max_length=100),
        ),
    ]
