# Generated by Django 4.1.2 on 2023-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(max_length=500),
        ),
    ]
